version: "2"

linters:
  default: standard
  enable:
    - dupl
    - gocritic
    # TODO: Enable gocyclo after refactoring isopen.
    # - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - unconvert
    - unparam
  settings:
    dupl:
      threshold: 100
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    rules:
      - text: weak cryptographic primitive
        linters:
          - gosec
    paths:
      - ^passes/bodyclose/testdata/

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - ^passes/bodyclose/testdata/
