name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: v2.13.2
